config/routes.rb
Rails.application.routes.draw do
  resources :wedding_requests do
    member do
     post :accept
     post :reject
    end
  end

  resources :successes
  resources :pictures

  get 'home/index'

  resources :matches
 resources :profiles do
  collection do
    get :search
  end
  member do
    get :register
  end
 end

  root 'home#index'
  
  devise_for :users 
  

end

app/models/wedding_request.rb
class WeddingRequest < ActiveRecord::Base
  belongs_to :user, :foreign_key=>:sender_id, :class_name=>"WeddingRequest"
  belongs_to :user, :foreign_key=>:reciever_id, :class_name=>"WeddingRequest"
end

app/controllers/wedding_requests_controller.rb
class WeddingRequestsController < ApplicationController
  before_action :set_wedding_request, only: [:show, :edit, :update, :destroy, :accept, :reject]
  before_filter :authenticate_user!
  # GET /wedding_requests
  # GET /wedding_requests.json
  def index
    if params[:sent] == "true"
    @requests =  current_user.sent_requests
    else
      @requests =  current_user.recieve_requests
    end
  end

  # GET /wedding_requests/1
  # GET /wedding_requests/1.json
  def show
  end

  # GET /wedding_requests/new
  def new
    @wedding_request = WeddingRequest.new
  end

  # GET /wedding_requests/1/edit
  def edit
  end

  # POST /wedding_requests
  # POST /wedding_requests.json
  def create
    @wedding_request = WeddingRequest.new(wedding_request_params)

      already =  WeddingRequest.where(:sender_id=>@wedding_request.sender_id, :reciever_id=>@wedding_request.reciever_id).first
      if !already
        if @wedding_request.save
          WeddingRequest.create(:sender_id=>@wedding_request.reciever_id, :reciever_id=>@wedding_request.sender_id, :is_accepted=>true)
          if params[:profile]== "true"
           redirect_to profile_path(:id=>@wedding_request.reciever_id), notice: 'Wedding request was successfully sent.'
           else
           redirect_to search_profiles_path(params=>params), notice: 'Wedding request was successfully sent.'

           end 
        end
      else
         redirect_to search_profiles_path(:q=>params[:q]), alert: 'Wedding request already sent.' 
      end
         
  end

  # PATCH/PUT /wedding_requests/1
  # PATCH/PUT /wedding_requests/1.json
  def update
    respond_to do |format|
      if @wedding_request.update(wedding_request_params)
        format.html { redirect_to @wedding_request, notice: 'Wedding request was successfully updated.' }
        format.json { render :show, status: :ok, location: @wedding_request }
      else
        format.html { render :edit }
        format.json { render json: @wedding_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept
     @wedding_request.is_accepted = true
     @wedding_request.save
     redirect_to wedding_requests_path , notice: 'Wedding request accepted successfully.'
  end

  def reject
    @wedding_request.is_cancel = true
    @wedding_request.save
    redirect_to wedding_requests_path , notice: 'Wedding request rejected successfully.' 
  end
  # DELETE /wedding_requests/1
  # DELETE /wedding_requests/1.json
  def destroy
    @wedding_request.destroy
    respond_to do |format|
      format.html { redirect_to wedding_requests_url, notice: 'Wedding request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wedding_request
      @wedding_request = WeddingRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wedding_request_params
      params.require(:wedding_request).permit(:sender_id, :reciever_id, :is_accepted, :is_cancel)
    end
end

app/helpers/wedding_requests_helper.rb
module WeddingRequestsHelper
end

app/views/wedding_requests/_form.html.erb
<%= form_for(@wedding_request) do |f| %>
  <% if @wedding_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wedding_request.errors.count, "error") %> prohibited this wedding_request from being saved:</h2>

      <ul>
      <% @wedding_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :reciever_id %><br>
    <%= f.number_field :reciever_id %>
  </div>
  <div class="field">
    <%= f.label :is_accepted %><br>
    <%= f.check_box :is_accepted %>
  </div>
  <div class="field">
    <%= f.label :is_cancel %><br>
    <%= f.check_box :is_cancel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wedding_requests/edit.html.erb
<h1>Editing wedding_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @wedding_request %> |
<%= link_to 'Back', wedding_requests_path %>

app/views/wedding_requests/index.html.erb
<h2>Inbox</h2>
<%= link_to  'Received', wedding_requests_path ,:class=>"btn btn-primary"%>  
<%= link_to  'Sent', wedding_requests_path(:sent=>true) ,:class=>"btn btn-default"%>  

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>
      <% if params[:sent]=='true' %>
        Receiver 
        <% else %>
        Sender
        <% end %>
      </th>
      <th>Is accepted?</th>
       <% if params[:sent] !='true' %>
        <th>Action</th>
        <% end %>

    </tr>
  </thead>

  <tbody>
    <% @requests.each do |wedding_request| %>
      <tr>
        <td><%= link_to  User.find(wedding_request.sender_id).first_name, profile_path(wedding_request.sender_id) %> </td>
        <td>
          <%=wedding_request.is_accepted %>
        </td>
       <% if params[:sent] !='true' %>
         <td>

          <% if !wedding_request.is_accepted and  !wedding_request.is_cancel%>
         <%= link_to 'Accept', accept_wedding_request_path(wedding_request), method: :post, data: { confirm: 'Are you sure?' }  %> |
          <% end %>
          <% if !wedding_request.is_cancel and !wedding_request.is_accepted %>
            <%= link_to 'Reject', accept_wedding_request_path(wedding_request), method: :post, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/wedding_requests/new.html.erb
<h1>New wedding_request</h1>

<%= render 'form' %>

<%= link_to 'Back', wedding_requests_path %>

app/views/wedding_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @wedding_request.sender_id %>
</p>

<p>
  <strong>Reciever:</strong>
  <%= @wedding_request.reciever_id %>
</p>

<p>
  <strong>Is accepted:</strong>
  <%= @wedding_request.is_accepted %>
</p>

<p>
  <strong>Is cancel:</strong>
  <%= @wedding_request.is_cancel %>
</p>

<%= link_to 'Edit', edit_wedding_request_path(@wedding_request) %> |
<%= link_to 'Back', wedding_requests_path %>