config/routes.rb
Rails.application.routes.draw do
  resources :wedding_requests do
    member do
     post :accept
     post :reject
    end
  end

  resources :successes
  resources :pictures

  get 'home/index'

  resources :matches
 resources :profiles do
  collection do
    get :search
  end
  member do
    get :register
  end
 end

  root 'home#index'
  
  devise_for :users 
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!

  def index
  	if current_user
  		if !current_user.is_completed
  			redirect_to register_profile_path(current_user)
  		end


	  	gender = current_user.gender == "Male" ? "Female" : "Male"
      @all_recents = User.where(:gender=>gender).size
      @all_matches = User.where(:gender=>gender).size
	  	@recents = User.where(:gender=>gender).order('created_at DESC').limit(6)
	  	@matches = User.where(:gender=>gender).order('created_at ASC').limit(6)
	  end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if !user_signed_in? %>

<section id="home-section">
    <div class="container">
      <div class="row clearfix">
         
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"> 
          <!-- .form-subscribe -->
          <div class="form-subscribe">
            <div class="form-subscribe-content">
              <h4>Sign up for free!</h4>
              <div id="message"></div>
              <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html=>{:class=>"form-horizontal"}) do |f| %>
              <%= devise_error_messages! %>
                <div class="form-group">
                  <div class="col-sm-12">
                    <!-- <input type="text" class="form-control" id="user_first_name" name="user[firstname]" placeholder="First Name"> -->
                    <input autocomplete="off" class="form-control" id="user_first_name" name="user[first_name]" type="text" placeholder="First Name">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12">
                   <!-- ÷ <input type="text" class="form-control" id="lastname" name="name" placeholder="Last Name"> -->
                   <input autocomplete="off" class="form-control" id="user_last_name" name="user[last_name]" type="text" placeholder="Last Name">
                  </div>
                </div>
                 <div class="form-group">
                  <div class="col-sm-12">
                    <input type="email" class="form-control" id="user_email" name="user[email]" placeholder="Your email">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12">
                    <input type="password" class="form-control" id="user_password" name="user[password]" placeholder="Password">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12">
                    <input type="password" class="form-control" id="user_password_confirmation" name="user[password_confirmation]" placeholder="Confirm Password">
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-sm-12">
    <%= f.label :gender, "Male", :value => "Male"  %>
    <%= f.radio_button :gender, "Male", :checked => true %>
    <%= f.label :gender, "Female", :value => "Female" %>
    <%= f.radio_button :gender, "Female" %>
                  </div>
                </div>
               
                <div class="form-group">
                  <div class="div-center col-sm-12">
                    <p class="text-left">
                      <button type="submit" id="SendButton" name="submit" class="btn btn-action btn-success btn-lg"><strong>Sign up!</strong></button>
                      <a href="/users/sign_in" class="btn btn-action btn-primary btn-lg">Log in</a>
                      
                    </p>
                    <p class="text-left">
                      <%#= render "devise/shared/links" %>                 
                    </p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <!-- /.form-subscribe --> 
        </div>
      </div>
    </div>
  </section>

<style type="text/css">
.container{
width: 1320px;
}
</style>
<!-- 
<h2>Register!</h2>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true %></div>

  <div><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
    <%= f.password_field :password, autocomplete: "off" %></div>

  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

     <div><%= f.label :first_name %><br />
    <%= f.text_field :first_name, autocomplete: "off" %></div>


</div>
     <div><%= f.label :last_name %><br />
    <%= f.text_field :last_name, autocomplete: "off" %></div>
 
<div class="field">
    <%= f.label :gender %><br />
    <%= f.label :gender, "Male", :value => "Male"  %>
    <%= f.radio_button :gender, "Male" %>
    <%= f.label :gender, "Female", :value => "Female" %>
    <%= f.radio_button :gender, "Female", :checked => true %>
  </div>

  <div><%= f.label :profile_for %><br />
    <%= f.select :profile_for, options_for_select([["Select One", ""], "Self", "Son", "Daughter", "Brother", "Sister", "Friend", "Relative"]), :class => '' %>
    </div>

  <div><%= f.submit "Sign up" %></div>
  <hr>
<% end %>
<%= render "devise/shared/links" %> -->
<%else%>
<div class="row">
  <div class="col-xs-6 col-md-3">
    <h4>Welcome <%= current_user.first_name%>!</h4>
    <%= image_tag current_user.avatar.url(:profile) %>

  </div>
  <div class="col-xs-6 col-md-5">

  <div class="panel panel-default">
    <div class="panel-heading">Recently Joined (<%=@all_recents%>) <a href="/profiles/search?age=0&recent=true" class="pull-right">view all</a></div>
    <div class="panel-body">


    <div class="row">
      <% @recents.each do |x|%>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <a href="/profiles/<%=x.id%>">
            <img src="<%=x.avatar.url(:thumb)%>" class="img-circle"></a>
            <div class="caption">
            <h5><%= link_to x.first_name , profile_path(x)%>  </h5>
             <%= x.details%>
            </div>
          </div>

        </div>
      <% end %>

    </div>
     
    </div>
  </div>

   <div class="panel panel-default">
    
    <div class="panel-heading">My Matches (<%= @all_matches%>) <a href="/matches" class="pull-right">view all</a></div>
    <div class="panel-body">


    <div class="row">
      <% @matches.each do |x|%>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <a href="/profiles/<%=x.id%>">
            <img src="<%=x.avatar.url(:thumb)%>" class="img-circle"></a>
            <div class="caption">
            <h5><%= link_to x.first_name , profile_path(x)%>  </h5>
             <%= x.details%>
            </div>
          </div>

        </div>
      <% end %>

    </div>
     
    </div>
  </div>

     
  </div>
  <div class="col-xs-6 col-md-4">
   <div class="panel panel-default">
    <div class="panel-heading">Partner Search</div>
    <div class="panel-body">
      <form role="form" action='/profiles/search'>
        <div class="form-group">
          <label for="exampleInputEmail1">Age > </label>
          <%= select("", "age", (18..50).collect {|p| [ p ] }, {  :prompt=>"select age greater then "} , {:class=>"form-control"  })%>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Marital Status</label>
          <%= select("", "marital", ["Never Married", "Divorced", "Widowed", "Awaiting Divorce", "Annulled"], {:prompt=>"Doesn't Matter" } , {:class=>"form-control"  })%>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Religion </label>
          <input type="text" name="religeon" class="form-control" id="" placeholder="Enter Religon">
        </div>
        
        <div class="form-group">
          <label for="exampleInputEmail1">Community</label>
          <input type="text" name="community" class="form-control" id="" placeholder="Enter Community">
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Country</label>
           <%= country_select :living_in, {priority: %w(US CA), prompt: 'Please select a country'}, {:class=>"form-control"} %>

        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    </div>
  </div>
  </div>
</div>
<% end %>