config/routes.rb
Rails.application.routes.draw do
  resources :wedding_requests do
    member do
     post :accept
     post :reject
    end
  end

  resources :successes
  resources :pictures

  get 'home/index'

  resources :matches
 resources :profiles do
  collection do
    get :search
  end
  member do
    get :register
  end
 end

  root 'home#index'
  
  devise_for :users 
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, :styles => {:thumb => "200x150>", :medium => "800x600>", :gallery=>"653x400#"}
  belongs_to :user
  validates_presence_of :title
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => 'image/jpeg'
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!

	def new
		@picture = Picture.new
end
 
 def create
    
    @picture = Picture.new(picture_params)
    @picture.user_id  = current_user.id
    respond_to do |format|
      if @picture.save        
        format.html { redirect_to pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end
  
  def show
  end


def index
    @pictures = current_user.pictures
end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  private
   def set_user
      @picture = Picture.find(params[:id])
    end

  def picture_params
    params.require(:picture).permit(:user_id, :title, :image)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => {:multipart => :true}) do |f| %>
  
  
  <p class="required">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p>

  <p class="buttons">
    <%= f.submit "submit" %>
    <%= link_to_function 'Cancel', "$(this).parent('form').remove()" if request.xhr? %>
  </p>
<% end %>

app/views/pictures/_picture.html.erb
<% div_for picture do %>
  <div class="spinner"><div></div></div>
  <div class="image">
    <%= link_to image_tag(picture.image.url(:thmb)), picture.image.url(:medium), :title => picture.title, :rel => "lightbox[roadtrip]" %>
  </div>
  
  <div class="title"><%=h truncate(picture.title, :length => 30) %></div>
  
  <div class="actions">
    <%= link_to 'Edit', edit_picture_path(picture), :class => :edit %>
    <%= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete, :class => :delete %>
  </div>
<% end -%>

app/views/pictures/create.js.erb
<% if @picture.valid? %>
  insert_picture("<%= escape_javascript(render @picture) %>");
  
  <%
    flash.clear
    
    # setting up a new dummy image to reset the form
    @picture = Picture.new
  %>
<% end %>

replace_form('new_picture', "<%= escape_javascript(render('form')) %>");

app/views/pictures/destroy.js.erb
remove_picture(<%= @picture.id %>);

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/edit.js.erb
show_edit_form(<%= @picture.id %>, "<%= escape_javascript(render("form")) %>");

app/views/pictures/index.html.erb
<header class='page-header'>
  <h3>Galleries</h3>
  
</header>
<%= link_to 'Add Image', new_picture_path  , :class=>"btn btn-primary pull-right" %> 

<table class="table">
  <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        Image
      </th>
      <th>
        Action
      </th>

    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |p| %>
    <tr>
      <td><%= p.title%></td>

      <td><img src="<%=p.image.url(:thumb)%>" > </td>
      <td>  <%= link_to 'Delete', p , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    
    <% end %>
  </tbody>
</table>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<h1><%= @picture.title %></h1>

<% div_for @picture do %>
<p class="image">
  <%= link_to image_tag(@picture.image.url(:medium)), @picture.image.url %>
</p>
<% end -%>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/update.js.erb
<% if @picture.valid? %>
  <% flash.clear %>
  update_picture(<%= @picture.id %>, "<%= escape_javascript(render(@picture))%>");
<% else %>
  replace_form('edit_picture_<%= @picture.id%>', "<%= escape_javascript(render(@picture)) %>");
<% end -%>