config/routes.rb
Rails.application.routes.draw do
  resources :wedding_requests do
    member do
     post :accept
     post :reject
    end
  end

  resources :successes
  resources :pictures

  get 'home/index'

  resources :matches
 resources :profiles do
  collection do
    get :search
  end
  member do
    get :register
  end
 end

  root 'home#index'
  
  devise_for :users 
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WeddingBellz" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
     
     <style type="text/css">
      body
      {
        background-image: url();
      }
     </style>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >WeddingBellz</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
             
             <% if user_signed_in? %>
				<% if current_user.is_completed %>
          <li><%= link_to "My Profile",  profile_path(current_user) %></li>
          <li><%= link_to "Inbox",   wedding_requests_path %></li>
					<li><%= link_to "Search",  search_profiles_path %></li>
					<li><%= link_to "Matches",  matches_path %></li>
			    <li><%= link_to "Success Story", successes_path  %></li>
			    <li><%= link_to "Image Gallery", pictures_path  %></li>
         
          <% if current_user.admin? %>
          <li><%= link_to "My Profile",  profile_path(current_user) %></li>
          <% end %>
				<% end %>
				<li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
			<% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

     <!--  <footer>
        <p>&copy; Wedding Bells 2014</p>
      </footer>
 -->
    </div> <!-- /container -->

  </body>
</html>